/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-29 06:46:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import com.calm.webdb.util.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.Transaction;
import com.calm.webdb.entity.CategoryEntity;
import java.util.List;
import com.calm.webdb.entity.LanguageEntity;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.calm.webdb.entity.CategoryEntity");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("com.calm.webdb.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.calm.webdb.entity.LanguageEntity");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <title>Infinity | Add Books</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"assets/resources/infinity_logo2.svg\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row gy-3\">\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "dashBord.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-9 shadow\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 text-center\">\r\n");
      out.write("                            <label class=\"border-start border-start-5 border-5 border-success mt-4 mb-4 text-center col-12 fs-2 text-success\" style=\"background-color: #c5f0c7; height: 50px;\">\r\n");
      out.write("                                Add New Book\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-10 offset-1 border border-1 rounded main-body shadow\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <label class=\"form-label lbl1\">Select Book Category</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                                            <select class=\"form-select\" id=\"category\">\r\n");
      out.write("                                                <option value=\"0\">Select Category</option>\r\n");
      out.write("                                                ");

                                                    // Assuming Database is a Java class with a search method
                                                    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
                                                    Session session1 = sessionFactory.openSession();
                                                    Transaction transaction = session1.beginTransaction();

                                                    // Assuming your entity class is "Gender" and you have a Gender class mapped in Hibernate
                                                    List<CategoryEntity> categories = session1.createQuery("FROM CategoryEntity", CategoryEntity.class).list();


                                                    for (CategoryEntity category : categories) {
                                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <option value=\"");
      out.print( category.getId());
      out.write('"');
      out.write('>');
      out.print( category.getName());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                                                ");

                                                    }
                                                
      out.write("\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <label class=\"form-label lbl1\">Add Author</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"author\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <label class=\"form-label lbl1\">Add Publisher</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"publisher\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <hr class=\"hr-break-1\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12\">\r\n");
      out.write("                                                    <label class=\"form-label lbl1\">Add book title</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-12 mb-3\">\r\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" id=\"title\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12\">\r\n");
      out.write("                                                    <label class=\"form-label fw-bold lbl1\">Book Format</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                    <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"hformat\">\r\n");
      out.write("                                                    <label class=\"form-check-label\" for=\"hformat\">\r\n");
      out.write("                                                        Hardcover\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                    <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"eformat\">\r\n");
      out.write("                                                    <label class=\"form-check-label\" for=\"eformat\">\r\n");
      out.write("                                                        eBook\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <hr class=\"hr-break-1\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <label class=\"form-label fw-bold lbl1\">Condition</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                            <input class=\"form-check-input\" type=\"radio\" name=\"condition\" id=\"bn\" checked/>\r\n");
      out.write("                                                            <label class=\"form-check-label\" for=\"bn\">\r\n");
      out.write("                                                                Brand New\r\n");
      out.write("                                                            </label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                            <input class=\"form-check-input\" type=\"radio\" name=\"condition\" id=\"us\"/>\r\n");
      out.write("                                                            <label class=\"form-check-label\" for=\"us\">\r\n");
      out.write("                                                                Used\r\n");
      out.write("                                                            </label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <label class=\"form-label lbl1 fw-bold\">Select Language</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                                                            <select class=\"form-select\" id=\"lang\">\r\n");
      out.write("                                                                <option value=\"0\">Select Language</option>\r\n");
      out.write("                                                                ");

                                                                    List<LanguageEntity> languages = session1.createQuery("FROM LanguageEntity", LanguageEntity.class).list();

                                                                    transaction.commit();
                                                                    session1.close();

                                                                    for (LanguageEntity language : languages) {
                                                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                <option value=\"");
      out.print( language.getId());
      out.write('"');
      out.write('>');
      out.print( language.getName());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                                                                ");

                                                                    }
                                                                
      out.write("\r\n");
      out.write("                                                            </select>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <hr class=\"hr-break-1\"/>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- //k -->\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <!-- com -->\r\n");
      out.write("                                                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <label class=\"form-label fw-bold lbl1\">Edition</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                            <input class=\"form-check-input\" type=\"radio\" name=\"Edition\" id=\"fprint\" checked/>\r\n");
      out.write("                                                            <label class=\"form-check-label\" for=\"fprint\">\r\n");
      out.write("                                                                First Print\r\n");
      out.write("                                                            </label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"offset-1 col-11 col-lg-3 ms-5 form-check\">\r\n");
      out.write("                                                            <input class=\"form-check-input\" type=\"radio\" name=\"Edition\" id=\"rprint\"/>\r\n");
      out.write("                                                            <label class=\"form-check-label\" for=\"rprint\">\r\n");
      out.write("                                                                Reprint\r\n");
      out.write("                                                            </label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!-- com -->\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                                        <label class=\"form-label fw-bold lbl1\">Pages</label>\r\n");
      out.write("                                                        <input type=\"number\" class=\"form-control\" value=\"0\" min=\"0\" id=\"pages\"/>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <hr class=\"hr-break-1\"/>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <label class=\"form-label fw-bold lbl1\">Description</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div clas=\"col-12\">\r\n");
      out.write("                                                <textarea class=\"form-control\" cols=\"30\" rows=\"25\" id=\"description\"></textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <hr class=\"hr-break-1\"/>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <label class=\"form-label fw-bold lbl1\">Add images</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"offset-lg-3 col-12 col-lg-6\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-4 offset-lg-4 border border-primary rounded\">\r\n");
      out.write("                                                <img class=\"img-fluid\" src=\"assets/resources/addproduct/addproductimg.svg\" id=\"preview0\" style=\"width: 250px;\"/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 offset-lg-3 col-lg-6 d-grid mt-3\">\r\n");
      out.write("\r\n");
      out.write("                                        <input type=\"file\" accept=\"img/*\" class=\"d-none\" id=\"imageuploader\" multiple/>\r\n");
      out.write("                                        <label for=\"imageuploader\" class=\"col-12 btn btn-primary\" onclick=\"changeProductImage();\">Upload image</label>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <hr class=\"hr-break-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"offset-lg-4 col-12 col-lg-4 d-grid mb-3 mt-2\">\r\n");
      out.write("                                <button class=\"btn btn-success fw-bold\" onclick=\"addproduct();\">Add Book</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "modals.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/script.js\"></script>\r\n");
      out.write("<script src=\"assets/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("<script src=\"assets/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
