/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-29 08:20:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.calm.webdb.entity.EmployeeEntity;
import java.util.List;
import org.hibernate.SessionFactory;
import com.calm.webdb.util.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.Transaction;
import com.calm.webdb.entity.VendorEntity;
import com.calm.webdb.entity.PaymentTypeEntity;

public final class grn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("com.calm.webdb.entity.VendorEntity");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.calm.webdb.entity.PaymentTypeEntity");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("com.calm.webdb.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.calm.webdb.entity.EmployeeEntity");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<EmployeeEntity> employees = (List<EmployeeEntity>) session.getAttribute("a");
    if (employees != null) {
        for (EmployeeEntity employee : employees) {


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <title>Infinity | GRN</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"assets/resources/infinity_logo2.svg\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row gy-3\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 text-center\">\r\n");
      out.write("            <h2 class=\"h2 text-success fw.bold\">Create New GRN</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 shadow\" style=\"background-color: rgb(234, 238, 195);\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label lbl1 fw-bold\">Select Vendor</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                            <select class=\"form-select\" id=\"vendor\">\r\n");
      out.write("                                <option value=\"0\">Select Vendor</option>\r\n");
      out.write("                                ");

                                    // Assuming Database is a Java class with a search method
                                    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
                                    Session session1 = sessionFactory.openSession();
                                    Transaction transaction = session1.beginTransaction();

                                    // Assuming your entity class is "Gender" and you have a Gender class mapped in Hibernate
                                    List<VendorEntity> vendors = session1.createQuery("FROM VendorEntity", VendorEntity.class).list();


                                    for (VendorEntity vendor : vendors) {
//                                    System.out.println(gender.getId()+" : "+gender.getName());
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print( vendor.getId());
      out.write('"');
      out.write('>');
      out.print( vendor.getName());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <button class=\"btn btn-primary mt-3 search-btn col-12\" onclick=\"testModal();\">Select Book</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label lbl1 fw-bold\">Book ID</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label lbl1 fw-bold\">Book Name</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 mb-2\">\r\n");
      out.write("                            <label class=\"form-label lbl1\" id=\"bookID\">None</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 mb-2\">\r\n");
      out.write("                            <label class=\"form-label lbl1\" id=\"bookName\">None</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <label class=\"form-label fw-bold lbl1\">Add Quantity</label>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" value=\"0\" min=\"0\" id=\"qty\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr/>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label fw-bold lbl1\">Delivery Costs</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 offset-lg-1 col-lg-3\">\r\n");
      out.write("                                    <label >Delivery cost within Colombo</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                                    <div class=\"input-group mb-3\">\r\n");
      out.write("                                        <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" aria-label=\"Amount (to the nearest rupee)\" id=\"dwc\">\r\n");
      out.write("                                        <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 offset-lg-1 col-lg-3\">\r\n");
      out.write("                                    <label >Delivery cost out of Colombo</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                                    <div class=\"input-group mb-3\">\r\n");
      out.write("                                        <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" aria-label=\"Amount (to the nearest rupee)\" id=\"doc\">\r\n");
      out.write("                                        <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr/>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label fw-bold lbl1\">Buying Price</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" aria-label=\"Amount (to the nearest rupee)\" id=\"bprice\">\r\n");
      out.write("                            <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label fw-bold lbl1\">Selling Price</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" aria-label=\"Amount (to the nearest rupee)\" id=\"sprice\">\r\n");
      out.write("                            <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <button class=\"btn btn-primary mt-3 search-btn col-12\" onclick=\"addtogrn();\">Add to GRN</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <table class=\"table\" id=\"grntable\">\r\n");
      out.write("                <thead>\r\n");
      out.write("\r\n");
      out.write("                <tr class=\"border border-1 border-white\">\r\n");
      out.write("                    <th class=\"text-center\">Book ID</th>\r\n");
      out.write("                    <th class=\"text-center\">Book Name</th>\r\n");
      out.write("                    <th class=\"text-center\">Quantity</th>\r\n");
      out.write("                    <th class=\"text-center\">Delivery Fee Colombo</th>\r\n");
      out.write("                    <th class=\"text-center\">Delivery Fee Other</th>\r\n");
      out.write("                    <th class=\"text-center\">Buying Price</th>\r\n");
      out.write("                    <th class=\"text-center\">Selling Price</th>\r\n");
      out.write("                    <th class=\"text-center\">Total</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody class=\"text-black fs-3 fw-bold\">\r\n");
      out.write("                <!-- <tr style=\"height: 72px;\">\r\n");
      out.write("                    <td class=\"bg-primary text-white fs-3\">001</td>\r\n");
      out.write("                    <td class=\"bg-primary text-white fs-3\">Mother</td>\r\n");
      out.write("                    <td class=\"fw-bold fs-6 text-end pt-3 bg-secondary text-white\">Hasitha</td>\r\n");
      out.write("                    <td class=\"fw-bold fs-6 text-end pt-3\">5</td>\r\n");
      out.write("                    <td class=\"fw-bold fs-6 text-end bg-primary text-white\">Rs. 300 .00</td>\r\n");
      out.write("                    <td class=\"fw-bold fs-6 text-end bg-primary text-white\">Rs. 500 .00</td>\r\n");
      out.write("                    <td class=\"fw-bold fs-6 text-end bg-primary text-white\">Rs. 1500 .00</td>\r\n");
      out.write("                </tr> -->\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("                <!-- <tfoot>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                    <td class=\"fs-5 text-end\">SUBTOTAL</td>\r\n");
      out.write("                    <td class=\"text-end\" id=\"subtotal\">Rs. 0 .00</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                    <td class=\"fs-5 text-end \">Discount</td>\r\n");
      out.write("                    <td class=\"text-end \">Rs. 200 .00</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                    <td class=\"fs-5 text-end text-white fw-bold\">GRAND TOTAL</td>\r\n");
      out.write("                    <td class=\"fs-5 text-end text-white fw-bold\">Rs. 1300 .00</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                </tfoot> -->\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-4 offset-lg-8 shadow\" style=\"background-color: rgb(234, 238, 195);\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 fs-5\">\r\n");
      out.write("                    <label class=\"form-label lbl1 text-black col-6 fs-6\">SUBTOTAL</label>\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <label class=\"form-label lbl1 text-black col-2 fs-6\">Rs.</label>\r\n");
      out.write("                        <label class=\"form-label lbl1 text-black col-2 fs-6\" id=\"subtotal\">0</label>\r\n");
      out.write("                        <label class=\"form-label lbl1 text-black col-2 fs-6\">.00</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <hr/>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 shadow\" style=\"background-color: rgb(234, 238, 195);\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label lbl1 fw-bold\">Select Payment Type</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 mb-3\">\r\n");
      out.write("                            <select class=\"form-select\" id=\"ptype\">\r\n");
      out.write("                                ");

                                    List<PaymentTypeEntity> paymentTypes = session1.createQuery("FROM PaymentTypeEntity", PaymentTypeEntity.class).list();

                                    transaction.commit();
                                    session1.close();

                                    for (PaymentTypeEntity paymentType : paymentTypes) {
//                                    System.out.println(gender.getId()+" : "+gender.getName());
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print( paymentType.getId());
      out.write('"');
      out.write('>');
      out.print( paymentType.getName());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label fw-bold lbl1\">Payment</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" aria-label=\"Amount (to the nearest rupee)\" onkeyup=\"balanceCal();\" id=\"payment\">\r\n");
      out.write("                            <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label fw-bold lbl1\">Balance</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <span class=\"input-group-text\">Rs.</span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control bg-transparent\" aria-label=\"Amount (to the nearest rupee)\" id=\"balance\" disabled>\r\n");
      out.write("                            <span class=\"input-group-text\">.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6 mb-5\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <button class=\"btn btn-success mt-3 search-btn col-12\" onclick=\"creategrn();\">Print GRN</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bookSelectModal.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/script.js\"></script>\r\n");
      out.write("<script src=\"assets/js/grnScript.js\"></script>\r\n");
      out.write("<script src=\"assets/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("<script src=\"assets/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

    }
}else{

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    alert(\"Please Sign In First\");\r\n");
      out.write("    // window.location = \"adminSignin.php\";\r\n");
      out.write("    fetch(\"adminSignIn\", {\r\n");
      out.write("        method: \"GET\"\r\n");
      out.write("    }).then(response => response.text())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            document.open();\r\n");
      out.write("            document.write(data);\r\n");
      out.write("            document.close();\r\n");
      out.write("        });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
