/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-01 06:13:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import org.hibernate.SessionFactory;
import com.calm.webdb.util.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.query.Query;
import com.calm.webdb.entity.*;

public final class singleProductView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.calm.webdb.entity");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("com.calm.webdb.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String pid = request.getParameter("id");

    if (pid != null && !pid.isEmpty()) {

        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        Session session1 = sessionFactory.openSession();
        Transaction transaction = session1.beginTransaction();

        Query<StockEntity> query = session1.createQuery("SELECT s FROM StockEntity s " +
                        "INNER JOIN s.bookByBookId WHERE s.id = :id", StockEntity.class)
                .setParameter("id", pid);
        List<StockEntity> stockProducts = query.getResultList();

//        transaction.commit();
//        session1.close();
        for(StockEntity stockProduct : stockProducts){

//$product_rs = Database::search("SELECT `book`.`id` AS `book_id`,`book`.`category_id`,
//`book`.`pages`,`book`.`language_id`,`book`.`edition_id`,
//`book`.`author_id`,`book`.`title`,`stock`.`id` AS `stock_id`,`stock`.`selling_price`,`stock`.`qty`,`book`.`description`,
//`book`.`condition_id`,`book`.`status_id`,`book`.`publisher_id` FROM `stock` INNER JOIN `book` ON
//`stock`.`book_id`=`book`.`id` WHERE `stock`.`id`='".$pid."'");
//
//$product_num = $product_rs->num_rows;
//
//if($product_num == 1){
//
//$product_data = $product_rs->fetch_assoc();




      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Infinity | Single Product View</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"assets/resources/infinity_logo2.svg\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 mt-0 bg-white singleproduct\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 shadow\" style=\"padding: 11px;\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 order-1 shadow\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 col-lg-6 order-2 order-lg-1\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                ");

                    Query<ImagesEntity> query1 = session1.createQuery("SELECT i FROM ImagesEntity i " +
                                    "WHERE i.productId = :productid", ImagesEntity.class)
                            .setParameter("productid", stockProduct.getBookByBookId().getId());
                    List<ImagesEntity> images = query1.getResultList();
                    String productImgCode = null;
                    for(ImagesEntity image : images){
                       productImgCode = image.getCode();
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <li class=\"d-flex flex-column justify-content-center align-items-center\r\n");
      out.write("                                    border border-secondary mb-1\">\r\n");
      out.write("                                            <img src=\"");
      out.print( image.getCode() );
      out.write("\" class=\"img-thumbnail mt-1 mb-1\"\r\n");
      out.write("                                            style=\"height: 50vh;\" id=\"productImg\" />\r\n");
      out.write("                                        </li>\r\n");
      out.write("\r\n");
      out.write("                                        ");


                                         }

                                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-0 col-lg-6 order-2\"></div>\r\n");
      out.write("                                <hr class=\"order-3\"/>\r\n");
      out.write("                                <div class=\"col-12 order-4 shadow\" style=\"background-color: rgb(234, 238, 195);\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <span class=\"text-success fs-4\">Pages : ");
      out.print(stockProduct.getBookByBookId().getPages() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");

                                            Query<EditionEntity> query2 = session1.createQuery("SELECT i FROM EditionEntity i " +
                                                            "WHERE i.id = :editionId", EditionEntity.class)
                                                    .setParameter("editionId", stockProduct.getBookByBookId().getEditionId());
//                                            List<EditionEntity> editions = query2.getResultList();
                                            EditionEntity edition = query2.uniqueResult();
                                        
      out.write("\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <span class=\"text-success fs-4\">Edition : ");
      out.print( edition.getName() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");

                                            Query<LanguageEntity> query3 = session1.createQuery("SELECT i FROM LanguageEntity i " +
                                                            "WHERE i.id = :languageId", LanguageEntity.class)
                                                    .setParameter("languageId", stockProduct.getBookByBookId().getLanguageId());
                                            LanguageEntity language = query3.uniqueResult();
                                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <span class=\"text-success fs-4\">Language : ");
      out.print( language.getName() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");

                                            Query<BookConditionEntity> query4 = session1.createQuery("SELECT i FROM BookConditionEntity i " +
                                                            "WHERE i.id = :conditionId", BookConditionEntity.class)
                                                    .setParameter("conditionId", stockProduct.getBookByBookId().getConditionId());
                                            BookConditionEntity condition = query4.uniqueResult();
                                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <span class=\"text-success fs-4\">Condition : ");
      out.print( condition.getName() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <span class=\"text-success fs-4\">Description : ");
      out.print( stockProduct.getBookByBookId().getDescription() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <hr class=\"order-5\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 order-3 shadow\" style=\"background-color: rgb(234, 238, 195);\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark\">\r\n");
      out.write("                                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                                            <ol class=\"breadcrumb\">\r\n");
      out.write("                                                <li class=\"breadcrumb-item\"><a href=\"\">Home</a></li>\r\n");
      out.write("                                                <li class=\"breadcrumb-item active\" aria-current=\"page\">\r\n");
      out.write("                                                    Single Product View\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ol>\r\n");
      out.write("                                        </nav>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark\">\r\n");
      out.write("                                        <div class=\"col-12 my-2\">\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-success\" id=\"ptitle\">");
      out.print( stockProduct.getBookByBookId().getTitle() );
      out.write("</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");

                                        Query<AuthorEntity> query5 = session1.createQuery("SELECT i FROM AuthorEntity i " +
                                                        "WHERE i.id = :authorId", AuthorEntity.class)
                                                .setParameter("authorId", stockProduct.getBookByBookId().getAuthorId());
                                        AuthorEntity author = query5.uniqueResult();

                                        Query<PublisherEntity> query6 = session1.createQuery("SELECT i FROM PublisherEntity i " +
                                                        "WHERE i.id = :publisherId", PublisherEntity.class)
                                                .setParameter("publisherId", stockProduct.getBookByBookId().getPublisherId());
                                        PublisherEntity publisher = query6.uniqueResult();
                                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark\">\r\n");
      out.write("                                        <div class=\"col-12 my-2\">\r\n");
      out.write("                                            <div class=\"row g-2\">\r\n");
      out.write("                                                <div class=\"col-12 col-lg-12 border border-0 border-bottom-1 border-dark mb-2 text-center\">\r\n");
      out.write("                                                    <span class=\"fs-4 text-info\"><b>Author : </b>");
      out.print( author.getName() );
      out.write("</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-12 col-lg-12 border border-0 border-dark text-center\">\r\n");
      out.write("                                                    <span class=\"fs-4 text-success\"><b>Publisher : </b>");
      out.print( publisher.getName() );
      out.write("</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12 my-2\">\r\n");
      out.write("                            <span class=\"badge\">\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"bi bi-star-fill text-warning fs-5\"></i>\r\n");
      out.write("                            <i class=\"bi bi-star-fill text-warning fs-5\"></i>\r\n");
      out.write("                            <i class=\"bi bi-star-fill text-warning fs-5\"></i>\r\n");
      out.write("                            <i class=\"bi bi-star-fill text-warning fs-5\"></i>\r\n");
      out.write("                            <i class=\"bi bi-star-half text-warning fs-5\"></i>\r\n");
      out.write("\r\n");
      out.write("                            &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <label class=\"fs-5 text-dark fw-bold\">4.5 Stars | 35 Rating And Reviews</label>\r\n");
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark\">\r\n");
      out.write("                                        <div class=\"col-12 my-2\">\r\n");
      out.write("\r\n");
      out.write("                                            ");

                                                double price = stockProduct.getSellingPrice();
                                                double addingPrice = (price/100)*5;
                                                double newPrice = price + addingPrice;
                                                double difference = newPrice - price;
                                                double percentage = (difference/price)*100;
                                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-black\" >Rs. </span>\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-black\" id=\"unitprice\">");
      out.print( price );
      out.write("</span>\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-black\" >0</span>\r\n");
      out.write("                                            &nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-danger\"><del>Rs. ");
      out.print( newPrice );
      out.write("0</del></span>\r\n");
      out.write("                                            &nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
      out.write("                                            <span class=\"fs-4 fw-bold text-black-50\">Save Rs. ");
      out.print( difference );
      out.write('0');
      out.write(' ');
      out.write('(');
      out.print( percentage );
      out.write("%)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row border-bottom border-dark mb-3\">\r\n");
      out.write("                                        <div class=\"col-12 my-2\">\r\n");
      out.write("                                            <span class=\"fs-5 text-primary\"><b>In-stock : </b>");
      out.print( stockProduct.getQty() );
      out.write(" Items Available</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"offset-lg-2 col-12 col-lg-8 border border-1 border-danger rounded\">\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-3 col-lg-2 border-end border-1 border-danger\">\r\n");
      out.write("                                                            <img src=\"assets/resources/pricetag.png\" />\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-9 col-lg-10\">\r\n");
      out.write("                                                <span class=\"fs-5 fw-bold text-warning\">\r\n");
      out.write("                                                    Stand a chance to get 5% discount by using VISA or MASTER\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12 my-3\">\r\n");
      out.write("                                                    <div class=\"row g-2\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"border border-1 border-secondary rounded overflow-hidden\r\n");
      out.write("                                            float-start mt-1 position-relative product_qty\">\r\n");
      out.write("                                                            <div class=\"col-12\">\r\n");
      out.write("                                                                <span>Quantity : </span>\r\n");
      out.write("                                                                <input type=\"text\" class=\"border-0 fs-5 fw-bold text-start\"\r\n");
      out.write("                                                                       style=\"outline: none;\" pattern=\"[0-9]\" value=\"1\"\r\n");
      out.write("                                                                       onkeyup='check_value(");
      out.print( stockProduct.getQty() );
      out.write(");' id=\"qtyinput\"/>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"position-absolute qty_buttons\">\r\n");
      out.write("                                                                    <div class=\"justify-content-center d-flex flex-column align-items-center border border-1\r\n");
      out.write("                                                     border-secondary qty_inc\"><i class=\"bi bi-caret-up text-info fs-5\" onclick=\"qty_inc(");
      out.print( stockProduct.getQty() );
      out.write(");\"></i>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"justify-content-center d-flex flex-column align-items-center border border-1\r\n");
      out.write("                                                     border-secondary qty_inc\"><i class=\"bi bi-caret-down text-info fs-5\" onclick=\"qty_dec();\"></i>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"row\">\r\n");
      out.write("                                                            <div class=\"col-12 mt-5\">\r\n");
      out.write("                                                                <div class=\"row\">\r\n");
      out.write("                                                                    <div class=\"col-4 d-grid\">\r\n");
      out.write("                                                                        <button class=\"btn btn-success\" onclick=\"paynowproduct('");
      out.print( productImgCode );
      out.write('\'');
      out.write(',');
      out.print( stockProduct.getId() );
      out.write(");\">Buy Now</button>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"col-4 d-grid\">\r\n");
      out.write("\r\n");
      out.write("                                                                        ");

                                                                            List<UsersEntity> users = (List<UsersEntity>) session.getAttribute("u");
                                                                            boolean existUser = false;
                                                                            String userEmail = null;
                                                                            if (users != null) {
                                                                                for (UsersEntity user : users) {
                                                                                    existUser = true;
                                                                                    userEmail = user.getEmail();
                                                                                }
                                                                            }
                                                                            if(existUser){
                                                                        
      out.write("\r\n");
      out.write("                                                                        <a href=\"#\" onclick=\"addToCart(");
      out.print( stockProduct.getId() );
      out.write(");\" class=\"btn btn-danger col-12\">Add to Cart</a>\r\n");
      out.write("                                                                        ");

                                                                            }else{
                                                                        
      out.write("\r\n");
      out.write("                                                                        <a href=\"#\" class=\"btn btn-danger col-12\">Add to Cart</a>\r\n");
      out.write("                                                                        ");

                                                                            }
                                                                        
      out.write("\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"col-4 d-grid\">\r\n");
      out.write("                                                                        ");

                                                                            if(existUser){
                                                                                Query<WatchlistEntity> query7 = session1.createQuery("SELECT i FROM WatchlistEntity i " +
                                                                                                "WHERE i.stockId = :stockId AND i.usersEmail= :userEmail", WatchlistEntity.class)
                                                                                        .setParameter("stockId", stockProduct.getId())
                                                                                        .setParameter("userEmail", userEmail);
                                                                                List<WatchlistEntity> wls = query7.getResultList();
                                                                                boolean existWatchlist = false;
                                                                                for(WatchlistEntity wl : wls){
                                                                                    existWatchlist = true;
                                                                                }
                                                                            if(existWatchlist){
                                                                        
      out.write("\r\n");
      out.write("                                                                        <a class=\"btn btn-secondary col-12\" onclick='addToWatchlist(");
      out.print( stockProduct.getId() );
      out.write(");'>\r\n");
      out.write("                                                                            <i class=\"bi bi-heart-fill fs-5 text-danger\" id=\"heart");
      out.print( stockProduct.getId() );
      out.write("\"></i>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        ");

                                                                            }else{
                                                                        
      out.write("\r\n");
      out.write("                                                                        <a class=\"btn btn-secondary col-12\" onclick='addToWatchlist(");
      out.print( stockProduct.getId() );
      out.write(");'>\r\n");
      out.write("                                                                            <i class=\"bi bi-heart-fill fs-5 text-white\" id=\"heart");
      out.print( stockProduct.getId() );
      out.write("\"></i>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        ");

                                                                            }
                                                                          }else{
                                                                        
      out.write("\r\n");
      out.write("                                                                        <a class=\"btn btn-secondary col-12\" >\r\n");
      out.write("                                                                            <i class=\"bi bi-heart-fill fs-5 text-danger\"></i>\r\n");
      out.write("                                                                        </a>\r\n");
      out.write("                                                                        ");

                                                                         }

                                                                        
      out.write("\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 bg-white\">\r\n");
      out.write("                    <div class=\"row d-block me-0 mt-4 mb-3 border-bottom border-1 border-dark\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <span class=\"fs-3 fw-bold\">Related Items</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 bg-white\">\r\n");
      out.write("                    <div class=\"row g-2\">\r\n");
      out.write("\r\n");
      out.write("                        ");

                            Query<StockEntity> query8 = session1.createQuery("SELECT s FROM StockEntity s " +
                                            "INNER JOIN s.bookByBookId b " +
                                            "WHERE b.categoryId = :categoryid OR b.authorId= :authorId", StockEntity.class)
                                    .setParameter("categoryid", stockProduct.getBookByBookId().getCategoryId())
                                    .setParameter("authorId", stockProduct.getBookByBookId().getAuthorId())
                                    .setMaxResults(6);

                            List<StockEntity> relatedProducts = query8.getResultList();
                            for(StockEntity relatedProduct : relatedProducts){

                                Query<ImagesEntity> query9 = session1.createQuery("SELECT i FROM ImagesEntity i " +
                                                "WHERE i.productId = :productId", ImagesEntity.class)
                                        .setParameter("productId", relatedProduct.getBookByBookId().getId());
                                ImagesEntity relatetedProductImage = query9.uniqueResult();

                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"offset-1 offset-lg-1 col-4 col-lg-2\">\r\n");
      out.write("                            <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("                                <img src=\"");
      out.print( relatetedProductImage.getCode() );
      out.write("\" class=\"card-img-top\" style=\"width: 250px; height: 300px;\"/>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h4 class=\"card-title\">");
      out.print( relatedProduct.getBookByBookId().getTitle() );
      out.write("</h4>\r\n");
      out.write("                                    <span class=\"fs-5 fw-bold\">Rs. ");
      out.print( relatedProduct.getSellingPrice() );
      out.write("0</span>\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"row g-1\">\r\n");
      out.write("                                            <div class=\"col-12 d-grid\">\r\n");
      out.write("                                                <a href='singleProductView?id=");
      out.print( relatedProduct.getId() );
      out.write("' class=\"btn btn-primary\">Buy Now</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 d-grid\">\r\n");
      out.write("                                                <a class=\"btn btn-primary\" onclick=\"addToCart(");
      out.print( relatedProduct.getId() );
      out.write(");\">Add to Cart</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 d-grid\">\r\n");
      out.write("                                                ");

                                                    if(existUser){
                                                        Query<WatchlistEntity> query7 = session1.createQuery("SELECT i FROM WatchlistEntity i " +
                                                                        "WHERE i.stockId = :stockId AND i.usersEmail= :userEmail", WatchlistEntity.class)
                                                                .setParameter("stockId", relatedProduct.getId())
                                                                .setParameter("userEmail", userEmail);
                                                        List<WatchlistEntity> wls = query7.getResultList();
                                                        boolean existWatchlist = false;
                                                        for(WatchlistEntity wl : wls){
                                                            existWatchlist = true;
                                                        }
                                                        if(existWatchlist){
                                                
      out.write("\r\n");
      out.write("                                                <a class=\"btn btn-primary col-12 mt-1\" onclick='addToWatchlist(");
      out.print( relatedProduct.getId() );
      out.write(");'>\r\n");
      out.write("                                                    <i class=\"bi bi-heart-fill fs-5 text-danger\" id=\"heart");
      out.print( relatedProduct.getId() );
      out.write("\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                ");

                                                        }else{
                                                
      out.write("\r\n");
      out.write("                                                <a class=\"btn btn-primary col-12 mt-1\" onclick='addToWatchlist(");
      out.print( relatedProduct.getId() );
      out.write(");'>\r\n");
      out.write("                                                    <i class=\"bi bi-heart-fill fs-5 text-white\" id=\"heart");
      out.print( relatedProduct.getId() );
      out.write("\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                ");

                                                        }

                                                  }else{
                                                
      out.write("\r\n");
      out.write("                                                <button class=\"btn btn-primary\">\r\n");
      out.write("                                                    <i class=\"bi bi-heart-fill fs-4 text-danger\"></i>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                                ");

                                                  }
                                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");


                         }

                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row d-block me-0 mt-4 mb-3 border-bottom border-1 border-dark\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <span class=\"fs-4 fw-bold\">Product Details</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 bg-white\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-3\">\r\n");
      out.write("                                    <label class=\"form-label fs-4 fw-bold\">Brand :</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-9\">\r\n");
      out.write("                                    <label class=\"form-label fs-4\">Apple</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-3\">\r\n");
      out.write("                                    <label class=\"form-label fs-4 fw-bold\">Model :</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-9\">\r\n");
      out.write("                                    <label class=\"form-label fs-4\"> iPhone 12 </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <label class=\"form-label fs-4 fw-bold\">Description :</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <textarea class=\"form-control\" cols=\"60\" rows=\"10\" disable></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

        transaction.commit();
        session1.close();
      }
    }else{

      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert(\"Something went wrong.\");\r\n");
      out.write("    </script>\r\n");

    }

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
